print("friends' birthdays")
birthday1 = input("Enter friend 1's birthday: ")
birthday2 = input("Enter friend 2's birthday: ")
birthday3= input("Enter friend 3's birthday: ")
birthday4 = input("Enter friend 4's birthday: ")
birthday5 = input("Enter friend 5's birthday: ")
print("============================ ")
print("Friend 1's birthday:", birthday1)
print("Friend 2's birthday:", birthday2)
print("Friend 3's birthday:", birthday3)
print("Friend 4's birthday:", birthday4)
print("Friend 5's birthday:", birthday5)